
public enum NameCard {
     AS_Coeur,
     ROI_Coeur,
     DAME_Coeur,
     VALET_Coeur,
     DIX_Coeur,
//     NEUF_Coeur,
//     HUIT_Coeur,
//     SEPT_Coeur,
//     SIX_Coeur,
//     CINQ_Coeur,
//     QUATRE_Coeur,
//     TROIS_Coeur,
//     DEUX_Coeur,
     
     AS_Pique,
     ROI_Pique,
     DAME_Pique,
     VALET_Pique,
     DIX_Pique,
//     NEUF_Pique,
//     HUIT_Pique,
//     SEPT_Pique,
//     SIX_Pique,
//     CINQ_Pique,
//     QUATRE_Pique,
//     TROIS_Pique,
//     DEUX_Pique,
//     
     AS_Carreau,
     ROI_Carreau,
     DAME_Carreau,
     VALET_Carreau,
     DIX_Carreau,
//     NEUF_Carreau,
//     HUIT_Carreau,
//     SEPT_Carreau,
//     SIX_Carreau,
//     CINQ_Carreau,
//     QUATRE_Carreau,
//     TROIS_Carreau,
//     DEUX_Carreau,
     
     AS_Trefle,
     ROI_Trefle,
     DAME_Trefle,
     VALET_Trefle,
     DIX_Trefle,
//     NEUF_Trefle,
//     HUIT_Trefle,
//     SEPT_Trefle,
//     SIX_Trefle,
//     CINQ_Trefle,
//     QUATRE_Trefle,
//     TROIS_Trefle,
//     DEUX_Trefle,
}
